### ISSUE TITLE
Desenvolver as telas de Oficinas dentro do módulo Eventos

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/siscontrat2#12]

**Comment by LoreleiGab** [comment]
Falhas a corrigir:
* o campo "valor hora/aula" não pode ser do tipo numérico, pois é moeda;
* remover parágrafo de orientação sobre a descrição, pois aquela informação cabe somente a evento;
* ao gravar,  não exibe mensagem de erro ou sucesso;
* os seguintes campos não gravam ou não retornam valor: certificados, vagas, venda de material, forma de inscrição, início da inscrição, encerramento da inscrição e descrição.
* na tela de edição o campo encerramento de inscrição está desalinhado;
* a tela de edição da erro ao gravar.

**Comment by lucasdauto** [comment]
Corrigido erro ao gravar
