### ISSUE TITLE
Tela de ocorrencias

### ISSUE THREAD

**Issue by riquetinem** [igsis/siscontrat2#14]

**Comment by DiegoVSantos** [comment]
- [ ] **perfil=evento&p=ocorrencia_cadastro:** Função que marca o checkbox automaticamente executa apenas ao cursos sair do campo "data encerramento".

    Poderia executar no campo data inicio também? Pois caso não seja 
    temporada o usuário não vai clicar no outro campo.

- [ ] **perfil=evento&p=ocorrencia_cadastro:** Caso a instituição seja selecionada não possua "espaço" (exemplo "Espaços Abertos") vai dar falha na inserção.

- [ ] **perfil=evento&p=ocorrencia_lista:** Funcionamento dos botões "Duplicar" e "Apagar".

**Comment by riquetinem** [comment]
A box não está salvando

**Comment by riquetinem** [comment]
Teste ok
