### ISSUE TITLE
Cadastro de pessoas

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/siscontrat2#202]
Inicialmente fazer uma busca por cpf/cnpj. Se não  obtiver resultado, encaminhar para o cadastro. Caso tenha resultado, entrar para a tela de edição.

**Comment by BielMaggot** [comment]
precisa arrumar a foto

**Comment by riquetinem** [comment]
teste ok

**Comment by riquetinem** [comment]
Tem que deixar o cadastro igual ao evento, nao ao de formação
