### ISSUE TITLE
trocar o status de formação do capac

### ISSUE THREAD

**Issue by riquetinem** [igsis/siscontrat2#297]
![image](https://app.gitkraken.com/api/glo/boards/5ce2bad0a9127a000f770676/attachments/5df07ffd5b8585000f22cfa3)

Pelo q eu vi, teve alteração na tabela "formação_cadastro" e vai ter que armazenar em outra tabela

**Comment by lucasdauto** [comment]
Task antiga e não foi possível localizar o erro citado, provavelmente já foi resolvida
