### ISSUE TITLE
Relatórios

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/siscontrat2#316]
PF
- [x] Pedido de pagamento parcelado (Word)
- [x] Pedido de pagamento integral (Word)
- [x] Recibo de pagamento parcelado (Word)
- [x] Recibo de pagamento integral (Word)
- [x] Ateste - documentaçãp (HTML)
- [x] Confirmação de serviço (HTML)
- [x] Recibo de entrega de nota de empenho (PDF)
- [x] Recibo de entrega de nota de liquidação (PDF)

PJ
- [x] Pedido de pagamento parcelado (Word)
- [x] Pedido de pagamento integral (Word)
- [x] Ateste - documentaçãp (HTML)
- [x] Confirmação de serviço (HTML)
- [x] Minuta acima de R$ 176 mil
- [x] Instruções para emissão de Nota Fiscal Integral
- [x] Instruções para emissão de Nota Fiscal Parcelado
- [x] Declaração Simples
- [x] Declaração de Associação sem fins lucrativos
- [x] Email Empresas
- [x] Email Cooperativas
- [x] Email Associações e institutos
- [x] Email Empresas com Minuta de Contrato
- [x] Recibo de entrega de nota de empenho (PDF)
- [x] Recibo de entrega de nota de liquidação (PDF)

**Comment by BielMaggot** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5ce2bad0a9127a000f770676/attachments/5e6fb0e8ec64f000118f6c11)
![image](https://app.gitkraken.com/api/glo/boards/5ce2bad0a9127a000f770676/attachments/5e6fb0ce1332eb001111e607)

**Comment by BielMaggot** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5ce2bad0a9127a000f770676/attachments/5e6fbfceec64f000118f6f73)
![image](https://app.gitkraken.com/api/glo/boards/5ce2bad0a9127a000f770676/attachments/5e6fbfdb1332eb001111e954)

**Comment by lucasdauto** [comment]
Task muito antiga, por isso está sendo fechada
