### ISSUE TITLE
Aviso de Contratação acima de valores anteriores

### ISSUE THREAD

**Issue by riquetinem** [igsis/siscontrat2#4]
Emitir um aviso aos programadores caso insiram um valor de cachê para o proponente contratado maior do que o valor inserido em contratações anteriores do mesmo proponente

**Comment by LoreleiGab** [comment]
Ao gravar um valor na atração, deve-se alertar se a atração atual tem valor acima de outras atrações com o mesmo nome realizadas anteriormente.
