### ISSUE TITLE
Verificar nas tabelas o motivo por não aparecer a opção de reordenar

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/siscontrat2#48]

**Comment by riquetinem** [comment]
(page)
<table id="tblLicitacao" class="table table-bordered table-striped">

(script nas pages)
<script defer src="../visual/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script defer src="../visual/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    $(function () {
        $('#tblLicitacao').DataTable({
            "language": {
                "url": 'bower_components/datatables.net/Portuguese-Brasil.json'
            },
            "responsive": true,
            "dom": "<'row'<'col-sm-6'l><'col-sm-6 text-right'f>>" +
                "<'row'<'col-sm-12'tr>>" +
                "<'row'<'col-sm-5'i><'col-sm-7 text-right'p>>",
        });
    });

**Comment by riquetinem** [comment]
teste ok
