### ISSUE TITLE
Evento - Acompanhar pedidos enviados

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/siscontrat2#68]
Lista com todos os pedidos enviados que tenha contratação artística onde foi o usuário logado que cadastrou ou está como fiscal ou suplente daquele evento. deve conter: Protocolo, número de processo, proponente, objeto, local, valor, período e status

**Comment by riquetinem** [comment]
PERFIS
COM
CON
CON | PAG
CONL |EMIA | EVE
CONL |EVE			
CONL | EVE | FOR			
CONL | EVE | OCP | PRO			
COO					
JUR					

DESCRIÇÃO DOS PERFIS
com -> comunicação
con -> contratos
conl -> contratos lite
eve -> eventos
for -> formação
ocp -> ocupação | Evento interno 
pro -> produção
coo -> coordenadoria
jur -> jurídico
pag -> pagamentos
pes -> pesquisa
adm -> administrador
