### ISSUE TITLE
Editar ocorrência , após cadastro de uma nova ocorrência

### ISSUE THREAD

**Issue by Ajujuba** [igsis/siscontrat2#765]
Após cadastrar uma nova ocorrencia de um evento do tipo filme aparece um erro de variavel não definida como mostrado na imagem a seguir.

![lucas2.jpg](https://app.gitkraken.com/api/glo/boards/5ce2bad0a9127a000f770676/attachments/5edfe5b9baee3c001115d6fa)

**Comment by lucasdauto** [comment]
Eu corrigi este problema antes da task ser lançada
